fixed math

diff --git a/gh-migrate-deploy-keys b/gh-migrate-deploy-keys
--- a/gh-migrate-deploy-keys
+++ b/gh-migrate-deploy-keys
@@ -125,8 +125,10 @@ LOG_FILE="${LOG_DIR}/gh-migrate-deploy-keys-${EPOCH_TIME}.log" # Set to default 
 SLEEP='300'                             # Number of seconds to sleep if out of API calls
 SLEEP_RETRY_COUNT='15'                  # Number of times to try to sleep before giving up
 SLEEP_COUNTER='0'                       # Counter of how many times we have gone to sleep
-API_REMAINING=0                         # Number of API calls remaining
-API_LIMIT_REMAINING=0                   # Number of API calls remaining before we hit the limit
+API_REMAINING_SOURCE=0                  # Number of API calls remaining
+API_LIMIT_REMAINING_SOURCE=0            # Number of API calls remaining before we hit the limit
+API_REMAINING_DESTINATION=0             # Number of API calls remaining
+API_LIMIT_REMAINING_DESTINATION=0       # Number of API calls remaining before we hit the limit
 ###########
 # GLOBALS #
 ###########
@@ -173,14 +175,14 @@ ValidateJQ() {
   fi
 }
 ################################################################################
-#### Function CheckAPILimit ####################################################
-CheckAPILimit() {
+#### Function CheckAPILimitDestination #########################################
+CheckAPILimitDestination() {
   ##############################################################
   # Check what is remaining, and if 0, we need to sleep it off #
   ##############################################################
   API_REMAINING_REQUEST=$(curl -s -X GET \
     --url "${GITHUB_API_URL}/rate_limit" \
-    -H "Authorization: Bearer ${GITHUB_TOKEN}")
+    -H "Authorization: Bearer ${DESTINATION_TOKEN}")
 
   Debug "DEBUG --- API REMAINING DATA BLOCK:"
   DebugJQ "${API_REMAINING_REQUEST}"
@@ -189,10 +191,10 @@ CheckAPILimit() {
     | jq -r '.message' 2>&1)
 
   if [[ "${API_REMAINING_MESSAGE}" != "Rate limiting is not enabled." ]]; then
-    API_REMAINING=$(echo "${API_REMAINING_REQUEST}" \
+    API_REMAINING_DESTINATION=$(echo "${API_REMAINING_REQUEST}" \
       | jq -r '.resources.graphql.remaining' 2>&1);
   else
-    API_REMAINING=9999999999
+    API_REMAINING_DESTINATION=9999999999
   fi
 
   #######################
@@ -205,14 +207,14 @@ CheckAPILimit() {
   ##############################
   if [ "${ERROR_CODE}" -ne 0 ]; then
     echo  "ERROR! Failed to get valid response back from GitHub API!"
-    echo "ERROR:[${API_REMAINING}]"
+    echo "ERROR:[${API_REMAINING_DESTINATION}]"
     exit 1
   fi
 
   ##########################################
   # Check to see if we have API calls left #
   ##########################################
-  if [[ "${API_REMAINING}" -eq 0 ]]; then
+  if [[ "${API_REMAINING_DESTINATION}" -eq 0 ]]; then
     # Increment the sleep counter
     ((SLEEP_COUNTER++))
     # Warn the user
@@ -229,14 +231,81 @@ CheckAPILimit() {
       # Get some sleep...
       sleep "${SLEEP}"
     fi
-  elif [[ "${API_REMAINING}" == 9999999999 ]]; then
+  elif [[ "${API_REMAINING_DESTINATION}" == 9999999999 ]]; then
     echo "API rate limiting is not enabled."
     # Set API limit remaining to the value we have
-    API_LIMIT_REMAINING="${API_REMAINING}"
+    API_LIMIT_REMAINING_DESTINATION="${API_REMAINING_DESTINATION}"
   else
-    echo "[${API_REMAINING}] API attempts remaining..."
+    echo "[${API_REMAINING_DESTINATION}] Destination API attempts remaining..."
     # Set API limit remaining to the value we have
-    API_LIMIT_REMAINING="${API_REMAINING}"
+    API_LIMIT_REMAINING_DESTINATION="${API_REMAINING_DESTINATION}"
+  fi
+}
+################################################################################
+#### Function CheckAPILimitSource ##############################################
+CheckAPILimitSource() {
+  ##############################################################
+  # Check what is remaining, and if 0, we need to sleep it off #
+  ##############################################################
+  API_REMAINING_REQUEST=$(curl -s -X GET \
+    --url "${GITHUB_API_URL}/rate_limit" \
+    -H "Authorization: Bearer ${SOURCE_TOKEN}")
+
+  Debug "DEBUG --- API REMAINING DATA BLOCK:"
+  DebugJQ "${API_REMAINING_REQUEST}"
+
+  API_REMAINING_MESSAGE=$(echo "${API_REMAINING_REQUEST}" \
+    | jq -r '.message' 2>&1)
+
+  if [[ "${API_REMAINING_MESSAGE}" != "Rate limiting is not enabled." ]]; then
+    API_REMAINING_SOURCE=$(echo "${API_REMAINING_REQUEST}" \
+      | jq -r '.resources.graphql.remaining' 2>&1);
+  else
+    API_REMAINING_SOURCE=9999999999
+  fi
+
+  #######################
+  # Load the error code #
+  #######################
+  ERROR_CODE=$?
+
+  ##############################
+  # Check the shell for errors #
+  ##############################
+  if [ "${ERROR_CODE}" -ne 0 ]; then
+    echo  "ERROR! Failed to get valid response back from GitHub API!"
+    echo "ERROR:[${API_REMAINING_SOURCE}]"
+    exit 1
+  fi
+
+  ##########################################
+  # Check to see if we have API calls left #
+  ##########################################
+  if [[ "${API_REMAINING_SOURCE}" -eq 0 ]]; then
+    # Increment the sleep counter
+    ((SLEEP_COUNTER++))
+    # Warn the user
+    echo "WARN! We have run out of GrahpQL calls and need to sleep!"
+    echo "Sleeping for ${SLEEP} seconds before next check"
+    # Check if we have slept enough
+    if [ "${SLEEP_COUNTER}" -gt "${SLEEP_RETRY_COUNT}" ]; then
+      # We have been doing this too long
+      echo "ERROR! We have tried to wait for:[$SLEEP_RETRY_COUNT] attempts!"
+      echo "ERROR! We only sleep for:[${SLEEP_COUNTER}] attempts!"
+      echo "Bailing out!"
+      exit 1
+    else
+      # Get some sleep...
+      sleep "${SLEEP}"
+    fi
+  elif [[ "${API_REMAINING_SOURCE}" == 9999999999 ]]; then
+    echo "API rate limiting is not enabled."
+    # Set API limit remaining to the value we have
+    API_LIMIT_REMAINING_SOURCE="${API_REMAINING_SOURCE}"
+  else
+    echo "[${API_REMAINING_SOURCE}] Source API attempts remaining..."
+    # Set API limit remaining to the value we have
+    API_LIMIT_REMAINING_SOURCE="${API_REMAINING_SOURCE}"
   fi
 }
 ################################################################################
@@ -662,9 +731,9 @@ DeleteKeyFromRepo() {
   KEY_VALUE="${5}"
 
   # Check if we have api limit avilable
-  if [ "${API_LIMIT_REMAINING}" -eq 0 ]; then
+  if [ "${API_LIMIT_REMAINING_SOURCE}" -eq 0 ]; then
     # Call check api to wait for the limit to reset
-    CheckApiLimit
+    CheckAPILimitSource
   else
     echo "----------------------------------------------------"
     echo "Deleting key:[${KEY_TITLE}] from repo:[${REPO_NAME}]"
@@ -702,7 +771,7 @@ DeleteKeyFromRepo() {
       echo "----------------------------------------------------"
       echo "Successfully deleted key:[${KEY_TITLE}] from repo:[${REPO_NAME}]"
       # Decrement the API limit
-      API_LIMIT_REMAINING=$((API_LIMIT_REMAINING-1))
+      API_LIMIT_REMAINING_SOURCE=$((API_LIMIT_REMAINING_SOURCE-1))
       {
         echo "Successfully deleted key:[${KEY_TITLE}] from repo:[${REPO_NAME}]"
         echo "----------------------------------------------------"
@@ -779,9 +848,9 @@ AddKeyToRepo() {
   echo "KEY_READ_ONLY:[${KEY_READ_ONLY}]"
 
   # Check if we have api limit avilable
-  if [ "${API_LIMIT_REMAINING}" -eq 0 ]; then
+  if [ "${API_LIMIT_REMAINING_DESTINATION}" -eq 0 ]; then
     # Call check api to wait for the limit to reset
-    CheckApiLimit
+    CheckAPILimitDestination
   else
     # Write the information to the log file
     {
@@ -818,7 +887,7 @@ AddKeyToRepo() {
       echo "----------------------------------------------------"
       echo "Successfully added key:[${KEY_TITLE}] to repo:[${REPO_NAME}]"
       # Decrement the API limit
-      API_LIMIT_REMAINING=$((API_LIMIT_REMAINING-1))
+      API_LIMIT_REMAINING_DESTINATION=$((API_LIMIT_REMAINING_DESTINATION-1))
       {
         echo "Successfully added key:[${KEY_TITLE}] to repo:[${REPO_NAME}]"
         echo "----------------------------------------------------"
@@ -855,7 +924,7 @@ GetKeyID() {
   KEY_ID=$(echo "${GET_KEYS_CMD}" | jq -r '.[] | select(.title == "'"${KEY_TITLE}"'") | .id')
 
   # Decrement the API limit
-  API_LIMIT_REMAINING=$((API_LIMIT_REMAINING-1))
+  API_LIMIT_REMAINING_SOURCE=$((API_LIMIT_REMAINING_SOURCE-1))
 
   # Return the key ID
   echo "${KEY_ID}"
@@ -888,7 +957,8 @@ ReadInputFile() {
     mapfile -t KEYS_ARRAY < <(GetDeployKeysFromRepo "${ORG_NAME}" "${REPO_NAME}")
 
     # Check the api limit
-    CheckAPILimit
+    CheckAPILimitSource
+    CheckAPILimitDestination
 
     # Check if the array is empty
     if [ "${#KEYS_ARRAY[@]}" -eq 0 ]; then
@@ -927,7 +997,8 @@ ReadInputFile() {
 #### Function ParseUpdateArray #################################################
 ParseUpdateArray() {
   # Check the API limit
-  CheckAPILimit
+  CheckAPILimitSource
+  CheckAPILimitDestination
   # Loop through the list of repos and update the visibility
   for OBJECT in "${UPDATE_ARRAY[@]}"; do
    # Create string for UPDATE_ARRAY
